### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Torppe/lautapelien-statsit#1]
# Katselmointi

Terve @Torppe! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Kirjauduin sisään
- Selasin pelejä ja lisäsin uuden pelin
- Lisäsin uuteen peliin muutaman pelaajan
- Tutkin pelin tilastoja
- Selailin pelaajia ja heidän tilastojaan
- Kirjauduin ulos

### Kokemus

- Hyvä sovellusidea, jota pystyy käyttämään ilman suurempia käytettävyysongelmia
- Pelien ja pelaajien tilastonäkymät ovat selkeät ja niissä on hyödyllistä tietoa
- [Etusivulla](https://frozen-dusk-07136.herokuapp.com/) voisi ehkä olla jotain mielenkiintoisempaa sisältöä
- Kirjautumislomake voisi antaa virheilmoituksen, jossa käyttäjätunnus tai salasana on väärä
- Pelin lisäämiseen voisi olla oma nappinsa jo ihan [saavutettavuuden](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) kannalta, jolloin vahvistusikkunaa ei välttämättä tarvitsisi ollenkaan. Lisäksi on hieman hämmentävää, että sivulta lähtedetään pois kun nimikenttä menettää fokuksen. 
- "Add a new match"-ikkunan "Submit"-painikkeen klikkaus ei tee mitään. Lisäksi "Submit"-teksti on hieman outo, käyttäjänä ihmettelen, että "mitä submitataan?"

## Koodi

- Frontti-puolen koodi on selkeästi organisoitua, hienoa!
- Hyvä idea abstraktoida API-kutsut omiksi palveluikseen ja käyttää `login` palvelua autentikaatio-operaatioihin ja tokenin ylläpitämiseen
- Kirjautuneen käyttäjän tietoihin tarkoitetut `localStorage`-operaatiot voisi siirtää (esim. [täällä](https://github.com/Torppe/lautapelien-statsit/blob/master/src/components/Login.js#L51)) komponenteista `login` palveluun
- Kirjautuneen käyttäjän tilaoperaatiot voisi `App` komponenttiin sijoitetun kontekstin avulla, jolloin `user` ja `setUser` propseja ei tarvitse valuttaa alaspäin puussa. Tässä hyvä arttikeli aiheesta: https://kentcdodds.com/blog/how-to-use-react-context-effectively 
- Myös backend-puolen koodi on selkeästi organisoitua, hyvää työtä!
- Kontrollereiden jatkuvista `try {} catch {}`-lohkoista (esim. [täällä](https://github.com/Torppe/tabletop-stats-backend/blob/master/controllers/playersRouter.js#L6)) pääsee kätevästi eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors) paketilla. Se nappaa middlewarejen käsittelemättömät virheet ja ohjaa ne virheet käsittelevään middlewareen
- Kontrollereissa erilliset `toJSON`-kutsut `res.json`-kutsun yhteydessä eivät ole tarpeen (esim. [täällä](https://github.com/Torppe/tabletop-stats-backend/blob/master/controllers/gamesRouter.js#L8)). `JSON.stringify`-metodi (jota express sisäisesti kutsuu, kun lähettää JSON-muotoisen vastauksen) kutsuu `toJSON`-metodeita automaattisesti. Lisätietoa asiasta: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
- Tokenin verifioinnin voisi eristää omaksi middlewarekseen, niin koodin duplikointi vähenisi

## Kokonaisuus

- Hyvä sovellusidea, jonka toiminnallisuutta pystyy käyttämään ilman erityisiä käytettävyysongelmia
- Koodi on erittäin hyvin organisoitua ja pääosin hyvälaatuista. Frontti-puolella komponenteista löytyvää sovelluslogiikka voisi paikoitellen entisestään abstraktoida palveluihin. Backend-puolen koodissakin vain pientä hienosäätöä.

**Comment by Torppe** [comment]
Moi,

Kiitos paljon kattavasta palautteesta! Pitänee ottaa parannusehdotukset käyttöön.
